spring.application.name=Hotel-Management

# Database Connection Settings
spring.datasource.url=jdbc:mysql://localhost:3306/hotel_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=tejas@1234_

# Hibernate Configuration (This tells Spring to auto-create your tables!)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.thymeleaf.cache=false